<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>await 的用法</title>
    <style>
      .ad {
        display: block;
        width: 300px;
        max-width: 100%;
        height: 150px;
        margin: 0 auto;
      }
      .none {
        display: none;
      }
    </style>
  </head>
  <body>
    <img id="ad" class="ad none" src="./ad.jpg" alt="前端体系课" />

    <script>
      // 1.await 的机制
      // async 函数中的代码有先后关系，await 会阻塞该 async 函数中代码的执行，async 函数外的代码不受影响
      // async 函数内部是同步执行的，它本身是异步的
      // function wait(ms) {
      //   return new Promise(resolve => {
      //     setTimeout(resolve, ms);
      //   });
      // }
      // async function ad() {
      //   const $ad = document.getElementById('ad');

      //   await wait(1000);
      //   // 显示广告
      //   $ad.classList.remove('none');

      //   await wait(2000);
      //   // 隐藏广告
      //   $ad.classList.add('none');

      //   // 相当于
      //   // wait(1000)
      //   //   .then(() => {
      //   //     // 显示广告
      //   //     $ad.classList.remove('none');

      //   //     return wait(2000);
      //   //   })
      //   //   .then(() => {
      //   //     // 隐藏广告
      //   //     $ad.classList.add('none');
      //   //   });
      // }
      // // ad();
      // console.log('async 函数外的代码');

      // 2.await 的值
      // 如果 await 后面是一个 Promise 对象，await 的值就是该 Promise 对象的结果（PromiseResult）
      // 如果 await 后面不是 Promise 对象，await 的值就是该值，相当于包了一层 Promise.resolve() 之后再获取该 Promise 对象的结果
      // function wait(ms, data) {
      //   return new Promise(resolve => {
      //     // setTimeout(resolve, ms);
      //     setTimeout(() => {
      //       // resolve(undefined)
      //       resolve(data);
      //     }, ms);
      //   });
      // }
      // async function ad() {
      //   const $ad = document.getElementById('ad');

      //   let result = await wait(1000, '开始显示广告');
      //   console.log(result);
      //   // console.log(await wait(1000));
      //   // 显示广告
      //   $ad.classList.remove('none');

      //   result = await wait(2000, '开始隐藏广告');
      //   console.log(result);
      //   // console.log(await wait(2000));
      //   // 隐藏广告
      //   $ad.classList.add('none');

      //   // 相当于
      //   // wait(1000, '开始显示广告')
      //   //   .then(result => {
      //   //     console.log(result);
      //   //     // 显示广告
      //   //     $ad.classList.remove('none');

      //   //     return wait(2000, '开始隐藏广告');
      //   //   })
      //   //   .then(result => {
      //   //     console.log(result);
      //   //     // 隐藏广告
      //   //     $ad.classList.add('none');
      //   //   });
      // }
      // // ad();

      async function fn() {
        // let result = await 123;
        // let result = await [1, 2, 3];
        // 相当于
        let result = await Promise.resolve([1, 2, 3]);
        console.log(result);
      }
      fn();

      // 3.await 的注意事项
      // 3.1.async 函数内部所有 await 后面的 Promise 对象都成功，async 函数返回的 Promise 对象才会成功；只要任何一个 await 后面的 Promise 对象失败，那么 async 函数返回的 Promise 对象就会失败
      // 可以通过 try...catch 或者 Promise...catch 的方式来处理错误
      function wait(ms, error) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            if (!error) {
              resolve();
            } else {
              reject(new Error(error));
            }
          }, ms);
        });
      }
      async function ad() {
        const $ad = document.getElementById('ad');

        // await wait(1000, '等1s失败了').catch(err => {
        //   console.log(err);
        // });
        // // 显示广告
        // $ad.classList.remove('none');

        // await wait(2000).catch(err => {
        //   console.log(err);
        // });
        // // 隐藏广告
        // $ad.classList.add('none');

        try {
          await wait(1000, '等1s失败了');
          // 显示广告
          $ad.classList.remove('none');

          await wait(2000);
          // 隐藏广告
          $ad.classList.add('none');
        } catch (error) {
          console.log(error, 'try...catch');
        }
      }
      // ad()
      //   .then(() => {
      //     console.log('success');
      //   })
      //   .catch(err => {
      //     console.log(err);
      //   });

      // 3.2.await 一般只能用在 async 函数中，async 函数中可以没有 await
      // 有的浏览器也可以用在模块的最顶层，借用 await 解决模块异步加载的问题
      // await 1
      // function fn() {
      //   await 1
      // }
      async function fn() {
        await 1;
      }
    </script>
    <script type="module">
      await 1;
    </script>
  </body>
</html>
